<?php
// Installer for Automated Report Card System - Processing Logic

session_start();

$action = $_GET['action'] ?? '';

// --- File Paths ---
$config_template_path = __DIR__ . '/../config/config.php'; // We'll read this to modify it
$config_file_path = __DIR__ . '/../config/config.php';
$sql_file_path = __DIR__ . '/../database.sql';


// --- Action Routing ---
switch ($action) {
    case 'setup_db':
        handle_database_setup();
        break;
    case 'create_admin':
        handle_admin_creation();
        break;
    default:
        $_SESSION['error'] = 'Invalid action.';
        header('Location: /install/index.php?step=1');
        exit;
}


// --- Handler Functions ---

/**
 * Handles Stage 2: Database setup, schema import, and config file creation.
 */
function handle_database_setup() {
    global $sql_file_path, $config_file_path;

    // Get POST data
    $db_host = $_POST['db_host'] ?? '';
    $db_name = $_POST['db_name'] ?? '';
    $db_user = $_POST['db_user'] ?? '';
    $db_pass = $_POST['db_pass'] ?? '';

    if (empty($db_host) || empty($db_name) || empty($db_user)) {
        $_SESSION['error'] = 'Database host, name, and user are required.';
        header('Location: /install/index.php?step=2');
        exit;
    }

    // 1. Test the connection
    try {
        $pdo = new PDO("mysql:host={$db_host}", $db_user, $db_pass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    } catch (PDOException $e) {
        $_SESSION['error'] = 'Could not connect to the database server. Please check your host, user, and password. Error: ' . $e->getMessage();
        header('Location: /install/index.php?step=2');
        exit;
    }

    // 2. Create the database if it doesn't exist
    try {
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$db_name}`");
        $pdo->exec("USE `{$db_name}`");
    } catch (PDOException $e) {
        $_SESSION['error'] = 'Could not create the database. Please ensure the user has CREATE DATABASE privileges. Error: ' . $e->getMessage();
        header('Location: /install/index.php?step=2');
        exit;
    }

    // 3. Import the SQL schema
    try {
        require_once __DIR__ . '/../core/helpers.php'; // Include the helper file
        import_sql_file($pdo, $sql_file_path);
    } catch (Exception $e) {
        $_SESSION['error'] = 'Could not import the database schema. Error: ' . $e->getMessage();
        header('Location: /install/index.php?step=2');
        exit;
    }

    // 4. Create the config.php file
    $config_content = <<<PHP
<?php
/**
 * config.php - Core Configuration File
 *
 * This file contains the core configuration settings for the ARS application,
 * including database credentials, application paths, and other essential constants.
 * THIS FILE WAS AUTOMATICALLY GENERATED BY THE INSTALLER.
 */

// --- Database Configuration ---
define('DB_HOST', '{$db_host}');
define('DB_USER', '{$db_user}');
define('DB_PASS', '{$db_pass}');
define('DB_NAME', '{$db_name}');

// --- Application Paths ---
define('APP_URL', 'http://' . \$_SERVER['HTTP_HOST'] . rtrim(dirname(dirname(\$_SERVER['SCRIPT_NAME'])), '/'));
define('APP_ROOT', dirname(__DIR__));

// --- Other Settings ---
date_default_timezone_set('UTC');
error_reporting(E_ALL);
ini_set('display_errors', 1); // Set to 0 in production

/**
 * Database Connection
 */
try {
    \$pdo = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, DB_PASS);
    \$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch(PDOException \$e) {
    die("ERROR: Could not connect to the database. " . \$e->getMessage());
}
?>
PHP;

    if (file_put_contents($config_file_path, $config_content) === false) {
        $_SESSION['error'] = 'Could not write to config.php. Please check file permissions.';
        header('Location: /install/index.php?step=2');
        exit;
    }

    // If all successful, move to the next step
    header('Location: /install/index.php?step=3');
    exit;
}


/**
 * Handles Stage 3: Super Admin account creation.
 */
function handle_admin_creation() {
    global $config_file_path;

    // Check if config exists first
    if (!file_exists($config_file_path)) {
        $_SESSION['error'] = 'Configuration file not found. Please complete the database setup first.';
        header('Location: /install/index.php?step=2');
        exit;
    }

    require_once $config_file_path;

    $admin_name = $_POST['admin_name'] ?? '';
    $admin_email = $_POST['admin_email'] ?? '';
    $admin_pass = $_POST['admin_pass'] ?? '';

    if (empty($admin_name) || empty($admin_email) || empty($admin_pass)) {
        $_SESSION['error'] = 'All fields are required to create the admin account.';
        header('Location: /install/index.php?step=3');
        exit;
    }

    if (!filter_var($admin_email, FILTER_VALIDATE_EMAIL)) {
        $_SESSION['error'] = 'Invalid email format provided.';
        header('Location: /install/index.php?step=3');
        exit;
    }

    try {
        $password_hash = password_hash($admin_pass, PASSWORD_BCRYPT);
        $sql = "INSERT INTO users (email, password, full_name, role) VALUES (:email, :password, :full_name, 'super_admin')";
        $stmt = $pdo->prepare($sql);
        $stmt->execute([
            ':email' => $admin_email,
            ':password' => $password_hash,
            ':full_name' => $admin_name
        ]);
    } catch (PDOException $e) {
        $_SESSION['error'] = 'Could not create the admin user. Error: ' . $e->getMessage();
        header('Location: /install/index.php?step=3');
        exit;
    }

    // If successful, move to the final step
    header('Location: /install/index.php?step=4');
    exit;
}
?>